//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoGeniX.Skinning.DefaultSkins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Office2007Silver {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Office2007Silver() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeoGeniX.Skinning.DefaultSkins.Office2007Silver", typeof(Office2007Silver).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CloseIcon {
            get {
                object obj = ResourceManager.GetObject("CloseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CloseIconSmall {
            get {
                object obj = ResourceManager.GetObject("CloseIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FormBorder {
            get {
                object obj = ResourceManager.GetObject("FormBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FormCaption {
            get {
                object obj = ResourceManager.GetObject("FormCaption", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FormCaptionButton {
            get {
                object obj = ResourceManager.GetObject("FormCaptionButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MaximizeIcon {
            get {
                object obj = ResourceManager.GetObject("MaximizeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MaximizeIconSmall {
            get {
                object obj = ResourceManager.GetObject("MaximizeIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MinimizeIcon {
            get {
                object obj = ResourceManager.GetObject("MinimizeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MinimizeIconSmall {
            get {
                object obj = ResourceManager.GetObject("MinimizeIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RestoreIcon {
            get {
                object obj = ResourceManager.GetObject("RestoreIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RestoreIconSmall {
            get {
                object obj = ResourceManager.GetObject("RestoreIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Skin&gt;
        ///    &lt;Meta&gt;
        ///        &lt;Name&gt;Office 2007 Silver&lt;/Name&gt;
        ///        &lt;Autor&gt;Daniel Kuschny&lt;/Autor&gt;
        ///    &lt;/Meta&gt;
        ///    &lt;Form&gt;
        ///        &lt;ActiveCaption&gt;53,110,170&lt;/ActiveCaption&gt;
        ///        &lt;InactiveCaption&gt;138,138,138&lt;/InactiveCaption&gt;
        ///        &lt;CenterCaption&gt;true&lt;/CenterCaption&gt;
        ///        &lt;Caption&gt;
        ///            &lt;Background&gt;
        ///                &lt;ImageSize&gt;15,30&lt;/ImageSize&gt;
        ///                &lt;ImagePadding&gt;6,5,6,2&lt;/ImagePadding&gt;
        ///            &lt;/Background&gt;
        ///            &lt;NormalButton&gt;
        ///                &lt;IconSize&gt;11,9&lt;/IconSize&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SkinDefinition {
            get {
                return ResourceManager.GetString("SkinDefinition", resourceCulture);
            }
        }
    }
}
