using System.Collections.Generic;

namespace CairoDesktop.Localization
{
    static class Language
    {
        public static Dictionary<string, string> en_US = new Dictionary<string, string>
        {
            { "sProgramsMenu", "Programs" },
            { "sPlacesMenu", "Places" },
            { "sCairoMenu_AboutCairo", "About Cairo" },
            { "sCairoMenu_CheckForUpdates", "Check for updates" },
            { "sCairoMenu_CairoSettings", "Cairo Settings" },
            { "sCairoMenu_WindowsControlPanel", "Windows Control Panel" },
            { "sCairoMenu_Run", "Run..." },
            { "sCairoMenu_TaskManager", "Task Manager" },
            { "sCairoMenu_ExitCairo", "Exit Cairo..." },
            { "sCairoMenu_Sleep", "Sleep" },
            { "sCairoMenu_Restart", "Restart..." },
            { "sCairoMenu_ShutDown", "Shut Down..." },
            { "sCairoMenu_LogOff", "Log Off..." },
            { "sAbout_Version", "Version" },
            { "sAbout_PreRelease", "Pre-release" },
            { "sAbout_Copyright", "Copyright © 2007-{0} Cairo Development Team and community contributors.  All rights reserved." },
            { "sInterface_OK", "OK" },
            { "sInterface_Cancel", "Cancel" },
            { "sInterface_Continue", "Continue" },
            { "sInterface_Finish", "Finish" },
            { "sInterface_Yes", "Yes" },
            { "sInterface_No", "No" },
            { "sInterface_Open", "Open" },
            { "sInterface_OpenWith", "Open with..." },
            { "sInterface_OpenAsAdministrator", "Open as administrator" },
            { "sInterface_Copy", "Copy" },
            { "sInterface_Paste", "Paste" },
            { "sInterface_Delete", "Delete" },
            { "sInterface_Rename", "Rename" },
            { "sInterface_Properties", "Properties" },
            { "sAppGrabber", "App Grabber" },
            { "sAppGrabber_PleaseWait", "Please wait while Cairo finds your apps..." },
            { "sAppGrabber_Page1Title", "Cairo has found the following applications installed on your computer." },
            { "sAppGrabber_Page1Line1", "Please drag applications you would like Cairo to store in your Programs menu to the left.  If you would like to keep applications out of this menu, please drag them to the right." },
            { "sAppGrabber_Page1Line2", "Cairo has pre-selected applications that might be useful for your Programs menu.  To add or remove applications from this menu at any time, run the App Grabber from the Cairo menu or simply drag items into the menu." },
            { "sAppGrabber_ProgramsMenuItems", "Programs Menu Items" },
            { "sAppGrabber_InstalledApplications", "Installed Applications" },
            { "sAppGrabber_Page2Title", "Categories" },
            { "sAppGrabber_Page2Line1", "Categories allow you to group applications by type so they are easier to find. Once you finish, you can add, remove, or edit categories and applications through the Programs menu itself. For convenience, you may also run the App Grabber from the Cairo menu." },
            { "sAppGrabber_Page2Directions", "Directions:" },
            { "sAppGrabber_Page2Directions1", "Drag and drop applications into the categories you desire." },
            { "sAppGrabber_Page2Directions2", "Click the plus button to add a new category." },
            { "sAppGrabber_Page2Directions3", "Click the X button on a category to delete it. (Applications in a deleted category will become uncategorized.)" },
            { "sAppGrabber_Page2Directions4", "Right-click a category to rename it." },
            { "sAppGrabber_Page2Directions5", "Click the \"Hide\" button to show only applications that need categorization." },
            { "sAppGrabber_Page2Directions6", "Items placed in the Quick Launch category will appear in the quick launch area of the Cairo taskbar. Items placed here will not be removed from the Programs menu.  To remove an item, drag it out from the Quick Launch category." },
            { "sAppGrabber_ProgramCategories", "Program Categories" },
            { "sAppGrabber_Hide", "Hide" },
            { "sAppGrabber_QuickLaunch", "Quick Launch" },
            { "sAppGrabber_Uncategorized", "Uncategorized" },
            { "sAppGrabber_All", "All" },
            { "sRun_Title", "Run" },
            { "sRun_Info", "Type the name of a program, folder, document, or Internet resource, and Cairo will open it for you." },
            { "sExitCairo_Title", "Are you sure you want to exit Cairo?" },
            { "sExitCairo_Info", "You will need to reboot or use the start menu shortcut in order to run Cairo again." },
            { "sExitCairo_ExitCairo", "Exit Cairo" },
            { "sLogoff_Title", "Are you sure you want to log off now?" },
            { "sLogoff_Info", "You will lose all unsaved documents and be logged off." },
            { "sRestart_Title", "Are you sure you want to restart now?" },
            { "sRestart_Info", "You will lose all unsaved documents and your computer will restart." },
            { "sRestart_Restart", "Restart" },
            { "sShutDown_Title", "Are you sure you want to shut down now?" },
            { "sShutDown_Info", "You will lose all unsaved documents and your computer will turn off." },
            { "sShutDown_ShutDown", "Shut Down" },
            { "sProgramsMenu_Empty", "No programs have been selected yet. Open App Grabber to get started!" },
            { "sProgramsMenu_UninstallAProgram", "Uninstall a Program" },
            { "sProgramsMenu_RemoveFromMenu", "Remove from menu" },
            { "sProgramsMenu_RemoveTitle", "Remove this app from the menu?" },
            { "sProgramsMenu_RemoveInfo", "\"{0}\" will be removed from the Programs menu. This will not uninstall the program." },
            { "sProgramsMenu_AlwaysAdminTitle", "Always run as administrator?" },
            { "sProgramsMenu_AlwaysAdminInfo", "You've run \"{0}\" as an administrator before. Would you like Cairo to automatically run it as an administrator every time?" },
            { "sProgramsMenu_Remove", "Remove" },
            { "sProgramsMenu_UWPInfo", "This is a Universal Windows Platform (UWP) application." },
            { "sPlacesMenu_Documents", "Documents" },
            { "sPlacesMenu_Downloads", "Downloads" },
            { "sPlacesMenu_Music", "Music" },
            { "sPlacesMenu_Pictures", "Pictures" },
            { "sPlacesMenu_Videos", "Videos" },
            { "sPlacesMenu_ThisPC", "This PC" },
            { "sPlacesMenu_ProgramFiles", "Program Files" },
            { "sPlacesMenu_RecycleBin", "Recycle Bin" },
            { "sStacks_Tooltip", "Drag directories here for easy access." },
            { "sStacks_OpenInNewWindow", "Open in new window" },
            { "sStacks_Remove", "Remove" },
            { "sStacks_Empty", "This folder is empty." },
            { "sMenuBar_OpenDateTimeSettings", "Open Date & Time Settings" },
            { "sMenuBar_ToggleNotificationArea", "Toggle notification area icons" },
            { "sSearch_Title", "Desktop Search" },
            { "sSearch_ViewAllResults", "View All Results" },
            { "sSearch_LastModified", "Last Modified: {0}" },
            { "sSearch_Error", "We were unable to open the search result." },
            { "sDesktop_Personalize", "Personalize" },
            { "sDesktop_DeleteTitle", "Are you sure you want to delete this?" },
            { "sDesktop_DeleteInfo", "\"{0}\" will be sent to the Recycle Bin." },
            { "sDesktop_BrowseTitle", "Select a folder to display as your desktop:" },
            { "sTaskbar_Empty", "Open windows to see them listed here." },
            { "sTaskbar_Minimize", "Minimize" },
            { "sTaskbar_Restore", "Restore" },
            { "sTaskbar_Close", "Close" },
            { "sError_OhNo", "Oops!" },
            { "sError_FileNotFoundInfo", "The file could not be found.  If you just removed this program, try removing it using the right-click menu to make the icon go away." },
            { "sSettings_General", "General" },
            { "sSettings_MenuBar", "Menu Bar" },
            { "sSettings_Desktop", "Desktop" },
            { "sSettings_Taskbar", "Taskbar" },
            { "sSettings_Appearance", "Appearance" },
            { "sSettings_Default", "Default" },
            { "sSettings_RestartCairo", "Restart Cairo to apply" },
            { "sSettings_Restarting", "Restarting..." },
            { "sSettings_General_UpdateCheck", "Automatically check for updates" },
            { "sSettings_General_Language", "Language:" },
            { "sSettings_General_Theme", "Theme:" },
            { "sSettings_General_ThemeTooltip", "Place themes into your Cairo installation directory." },
            { "sSettings_General_TimeFormat", "Time format:" },
            { "sSettings_General_TimeFormatTooltip", "Some values you can use here:&#x0a;d	Day of month&#x0a;ddd	Day of week&#x0a;h	Hour (12-hour)&#x0a;hh	Hour (12-hour, leading zero)&#x0a;H	Hour (24-hour)&#x0a;HH	Hour (24-hour, leading zero)&#x0a;m	Minutes&#x0a;mm	Minutes (leading zero)&#x0a;s	Seconds&#x0a;ss	Seconds (leading zero)&#x0a;tt	AM/PM if applicable" },
            { "sSettings_General_DateFormat", "Date format:" },
            { "sSettings_General_DateFormatTooltip", "Some values you can use here:&#x0a;d	Day of month&#x0a;dd	Day of month (leading zero)&#x0a;ddd	Weekday (abbreviated)&#x0a;dddd	Weekday (text)&#x0a;M	Month&#x0a;MM	Month (leading zero)&#x0a;MMM	Month (abbreviated)&#x0a;MMMM	Month (text)&#x0a;yy	Year (2-digit)&#x0a;yyyy	Year (4-digit)" },
            { "sSettings_General_FilesAndFolders", "Files and folders" },
            { "sSettings_General_ShowSubDirectories", "Show sub-directories" },
            { "sSettings_General_ShowFileExtensions", "Show file extensions" },
            { "sSettings_General_FileManager", "File manager:" },
            { "sSettings_MenuBar_DefaultProgramsCategory", "Default programs category:" },
            { "sSettings_MenuBar_EnableMenuBarShadow", "Enable Menu Bar shadow" },
            { "sSettings_MenuBar_NotificationArea", "Notification area" },
            { "sSettings_MenuBar_EnableNotificationArea", "Enable notification area" },
            { "sSettings_MenuBar_NotificationAreaError", "The notification area component could not be loaded. Please install the Microsoft Visual C++ 2015 Redistributable." },
            { "sSettings_MenuBar_ShowNotifyIcons", "Show notification area icons:" },
            { "sSettings_MenuBar_ShowNotifyIconsCollapsed", "Collapsed" },
            { "sSettings_MenuBar_ShowNotifyIconsAlways", "Always" },
            { "sSettings_MenuBar_PeriodicallyRehook", "Periodically re-establish notification area hook" },
            { "sSettings_Desktop_EnableDesktop", "Enable Desktop" },
            { "sSettings_Desktop_DesktopHome", "Desktop home:" },
            { "sSettings_Desktop_IconSize", "Icon size:" },
            { "sSettings_Desktop_IconSizeLarge", "Large" },
            { "sSettings_Desktop_IconSizeSmall", "Small" },
            { "sSettings_Desktop_LabelPosition", "Label position:" },
            { "sSettings_Desktop_LabelPositionRight", "Right" },
            { "sSettings_Desktop_LabelPositionBottom", "Bottom" },
            { "sSettings_Desktop_DynamicDesktop", "Dynamic Desktop" },
            { "sSettings_Desktop_EnableDynamicDesktop", "Use Dynamic Desktop" },
            { "sSettings_Taskbar_EnableTaskbar", "Enable Taskbar" },
            { "sSettings_Taskbar_TaskbarPosition", "Taskbar position:" },
            { "sSettings_Taskbar_PositionBottom", "Bottom" },
            { "sSettings_Taskbar_PositionTop", "Top" },
            { "sSettings_Taskbar_DisplayMode", "Display mode:" },
            { "sSettings_Taskbar_DisplayModeAppBar", "Taskbar reserves space" },
            { "sSettings_Taskbar_DisplayModeOverlap", "Taskbar overlaps windows" }
        };
    }
}
