using System.Collections.Generic;

namespace CairoDesktop.Localization
{
    static class Language
    {
        public static Dictionary<string, string> en_US = new Dictionary<string, string>
        {
            { "sProgramsMenu", "Programs" },
            { "sPlacesMenu", "Places" },
            { "sCairoMenu_AboutCairo", "About Cairo" },
            { "sCairoMenu_CheckForUpdates", "Check for updates" },
            { "sCairoMenu_CairoSettings", "Cairo Settings" },
            { "sCairoMenu_WindowsControlPanel", "Windows Control Panel" },
            { "sCairoMenu_WindowsSettings", "Windows Settings" },
            { "sCairoMenu_Run", "Run..." },
            { "sCairoMenu_TaskManager", "Task Manager" },
            { "sCairoMenu_ExitCairo", "Exit Cairo..." },
            { "sCairoMenu_Sleep", "Sleep" },
            { "sCairoMenu_Restart", "Restart..." },
            { "sCairoMenu_ShutDown", "Shut Down..." },
            { "sCairoMenu_LogOff", "Log Off..." },
            { "sAbout_Version", "Version" },
            { "sAbout_PreRelease", "Pre-release" },
            { "sAbout_Copyright", "Copyright © 2007-{0} Cairo Development Team and community contributors.  All rights reserved." },
            { "sInterface_OK", "OK" },
            { "sInterface_Cancel", "Cancel" },
            { "sInterface_Continue", "Continue" },
            { "sInterface_Finish", "Finish" },
            { "sInterface_Yes", "Yes" },
            { "sInterface_No", "No" },
            { "sInterface_Open", "Open" },
            { "sInterface_OpenWith", "Open with..." },
            { "sInterface_OpenAsAdministrator", "Open as administrator" },
            { "sInterface_RunAsUser", "Run as different user" },
            { "sInterface_AddToStacks", "Add to Stacks" },
            { "sInterface_Copy", "Copy" },
            { "sInterface_Paste", "Paste" },
            { "sInterface_Delete", "Delete" },
            { "sInterface_Rename", "Rename" },
            { "sInterface_Properties", "Properties" },
            { "sInterface_Browse", "Browse..." },
            { "sAppGrabber", "App Grabber" },
            { "sAppGrabber_PleaseWait", "Please wait while Cairo finds your apps..." },
            { "sAppGrabber_Page1Title", "Cairo has found the following applications installed on your computer." },
            { "sAppGrabber_Page1Line1", "Please drag applications you would like Cairo to store in your Programs menu to the left.  If you would like to keep applications out of this menu, please drag them to the right." },
            { "sAppGrabber_Page1Line2", "Cairo has pre-selected applications that might be useful for your Programs menu.  To add or remove applications from this menu at any time, run the App Grabber from the Cairo menu or simply drag items into the menu." },
            { "sAppGrabber_ProgramsMenuItems", "Programs Menu Items" },
            { "sAppGrabber_InstalledApplications", "Installed Applications" },
            { "sAppGrabber_Page2Title", "Categories" },
            { "sAppGrabber_Page2Line1", "Categories allow you to group applications by type so they are easier to find. Once you finish, you can add, remove, or edit categories and applications through the Programs menu itself. For convenience, you may also run the App Grabber from the Cairo menu." },
            { "sAppGrabber_Page2Directions", "Directions:" },
            { "sAppGrabber_Page2Directions1", "Drag and drop applications into the categories you desire." },
            { "sAppGrabber_Page2Directions2", "Click the plus button to add a new category." },
            { "sAppGrabber_Page2Directions3", "Click the X button on a category to delete it. (Applications in a deleted category will become uncategorized.)" },
            { "sAppGrabber_Page2Directions4", "Right-click a category to rename it." },
            { "sAppGrabber_Page2Directions5", "Click the \"Hide\" button to show only applications that need categorization." },
            { "sAppGrabber_Page2Directions6", "Items placed in the Quick Launch category will appear in the quick launch area of the Cairo taskbar. Items placed here will not be removed from the Programs menu.  To remove an item, drag it out from the Quick Launch category." },
            { "sAppGrabber_ProgramCategories", "Program Categories" },
            { "sAppGrabber_Hide", "Hide" },
            { "sAppGrabber_QuickLaunch", "Quick Launch" },
            { "sAppGrabber_Uncategorized", "Uncategorized" },
            { "sAppGrabber_All", "All" },
            { "sAppGrabber_Untitled", "Untitled" },
            { "sAppGrabber_Category_Accessories", "Accessories" },
            { "sAppGrabber_Category_Productivity", "Productivity" },
            { "sAppGrabber_Category_Development", "Development" },
            { "sAppGrabber_Category_Graphics", "Graphics" },
            { "sAppGrabber_Category_Media", "Media" },
            { "sAppGrabber_Category_Internet", "Internet" },
            { "sAppGrabber_Category_Games", "Games" },
            { "sRun_Title", "Run" },
            { "sRun_Info", "Type the name of a program, folder, document, or Internet resource, and Cairo will open it for you." },
            { "sExitCairo_Title", "Are you sure you want to exit Cairo?" },
            { "sExitCairo_Info", "You will need to reboot or use the start menu shortcut in order to run Cairo again." },
            { "sExitCairo_ExitCairo", "Exit Cairo" },
            { "sLogoff_Title", "Are you sure you want to log off now?" },
            { "sLogoff_Info", "You will lose all unsaved documents and be logged off." },
            { "sLogoff_Logoff", "Log Off" },
            { "sRestart_Title", "Are you sure you want to restart now?" },
            { "sRestart_Info", "You will lose all unsaved documents and your computer will restart." },
            { "sRestart_Restart", "Restart" },
            { "sShutDown_Title", "Are you sure you want to shut down now?" },
            { "sShutDown_Info", "You will lose all unsaved documents and your computer will turn off." },
            { "sShutDown_ShutDown", "Shut Down" },
            { "sProgramsMenu_Empty", "No programs have been selected yet. Open App Grabber to get started!" },
            { "sProgramsMenu_UninstallAProgram", "Uninstall a Program" },
            { "sProgramsMenu_RemoveFromMenu", "Remove from list" },
            { "sProgramsMenu_RemoveTitle", "Remove this app from the list?" },
            { "sProgramsMenu_RemoveInfo", "\"{0}\" will be removed from the {1} list. This will not uninstall the program." },
            { "sProgramsMenu_AlwaysAdminTitle", "Always run as administrator?" },
            { "sProgramsMenu_AlwaysAdminInfo", "You've run \"{0}\" as an administrator before. Would you like Cairo to automatically run it as an administrator every time?" },
            { "sProgramsMenu_Remove", "Remove" },
            { "sProgramsMenu_UWPInfo", "This is a Universal Windows Platform (UWP) application." },
            { "sProgramsMenu_AddToQuickLaunch", "Add to Quick Launch" },
            { "sPlacesMenu_Documents", "Documents" },
            { "sPlacesMenu_Downloads", "Downloads" },
            { "sPlacesMenu_Music", "Music" },
            { "sPlacesMenu_Pictures", "Pictures" },
            { "sPlacesMenu_Videos", "Videos" },
            { "sPlacesMenu_ThisPC", "This PC" },
            { "sPlacesMenu_ProgramFiles", "Program Files" },
            { "sPlacesMenu_RecycleBin", "Recycle Bin" },
            { "sStacks_Tooltip", "Drag directories here for easy access." },
            { "sStacks_OpenInNewWindow", "Open in new window" },
            { "sStacks_Remove", "Remove" },
            { "sStacks_Empty", "This folder is empty." },
            { "sMenuBar_OpenDateTimeSettings", "Open Date & Time settings" },
            { "sMenuBar_OpenActionCenter", "Open Action Center" },
            { "sMenuBar_ToggleNotificationArea", "Toggle notification area icons" },
            { "sMenuBar_Volume", "Volume" },
            { "sMenuBar_OpenSoundSettings", "Open Sound settings" },
            { "sSearch_Title", "Desktop Search" },
            { "sSearch_ViewAllResults", "View All Results" },
            { "sSearch_LastModified", "Last Modified: {0}" },
            { "sSearch_Error", "We were unable to open the search result." },
            { "sDesktop_Personalize", "Personalize" },
            { "sDesktop_DeleteTitle", "Are you sure you want to delete this?" },
            { "sDesktop_DeleteInfo", "\"{0}\" will be sent to the Recycle Bin." },
            { "sDesktop_BrowseTitle", "Select a folder to display as your desktop:" },
            { "sDesktop_CurrentFolder", "Current folder:" },
            { "sDesktop_Back", "Back" },
            { "sDesktop_Forward", "Forward" },
            { "sDesktop_Browse", "Choose folder" },
            { "sDesktop_Home", "Home" },
            { "sTaskbar_Empty", "Open windows to see them listed here." },
            { "sTaskbar_Minimize", "Minimize" },
            { "sTaskbar_Restore", "Restore" },
            { "sTaskbar_Close", "Close" },
            { "sTaskbar_TaskView", "Task View" },
            { "sTaskbar_TaskListToolTip", "Task List" },
            { "sTaskbar_DesktopOverlayToolTip", "Desktop Overlay" },
            { "sError_OhNo", "Oops!" },
            { "sError_FileNotFoundInfo", "The item could not be opened because it does not exist or Cairo does not have permission to open it." },
            { "sError_CantOpenAppWiz", "Unable to open the Programs and Features control panel." },
            { "sSettings_General", "General" },
            { "sSettings_MenuBar", "Menu Bar" },
            { "sSettings_Desktop", "Desktop" },
            { "sSettings_Taskbar", "Taskbar" },
            { "sSettings_Appearance", "Appearance" },
            { "sSettings_Advanced", "Advanced" },
            { "sSettings_Default", "Default" },
            { "sSettings_RestartCairo", "Restart Cairo to apply" },
            { "sSettings_Restarting", "Restarting..." },
            { "sSettings_General_UpdateCheck", "Automatically check for updates" },
            { "sSettings_General_Language", "Language:" },
            { "sSettings_General_Theme", "Theme:" },
            { "sSettings_General_ThemeTooltip", "Place themes into your Cairo installation directory." },
            { "sSettings_General_TimeFormat", "Time format:" },
            { "sSettings_General_TimeFormatTooltip", "Some values you can use here:\r\nd	Day of month\r\nddd	Day of week\r\nh	Hour (12-hour)\r\nhh	Hour (12-hour, leading zero)\r\nH	Hour (24-hour)\r\nHH	Hour (24-hour, leading zero)\r\nm	Minutes\r\nmm	Minutes (leading zero)\r\ns	Seconds\r\nss	Seconds (leading zero)\r\ntt	AM/PM if applicable" },
            { "sSettings_General_DateFormat", "Date format:" },
            { "sSettings_General_DateFormatTooltip", "Some values you can use here:\r\nd	Day of month\r\ndd	Day of month (leading zero)\r\nddd	Weekday (abbreviated)\r\ndddd	Weekday (text)\r\nM	Month\r\nMM	Month (leading zero)\r\nMMM	Month (abbreviated)\r\nMMMM	Month (text)\r\nyy	Year (2-digit)\r\nyyyy	Year (4-digit)" },
            { "sSettings_General_FilesAndFolders", "Files and folders" },
            { "sSettings_General_ShowSubDirectories", "Show sub-directories" },
            { "sSettings_General_ShowFileExtensions", "Show file extensions" },
            { "sSettings_General_ForceSoftwareRendering", "Force software rendering" },
            { "sSettings_General_FileManager", "File manager:" },
            { "sSettings_General_FoldersOpenDesktopOverlay", "Folders open using the dynamic desktop overlay" },
            { "sSettings_MenuBar_DefaultProgramsCategory", "Default programs category:" },
            { "sSettings_MenuBar_EnableMenuBarShadow", "Enable Menu Bar shadow" },
            { "sSettings_MenuBar_NotificationArea", "Notification area" },
            { "sSettings_MenuBar_EnableNotificationArea", "Enable notification area" },
            { "sSettings_MenuBar_NotificationAreaError", "The notification area component could not be loaded. Please install the Microsoft Visual C++ 2015 Redistributable." },
            { "sSettings_MenuBar_ShowNotifyIcons", "Show notification area icons:" },
            { "sSettings_MenuBar_ShowNotifyIconsCollapsed", "Collapsed" },
            { "sSettings_MenuBar_ShowNotifyIconsAlways", "Always" },
            { "sSettings_MenuBar_EnableCairoMenuHotKey", "Enable Cairo menu hotkey:" },
            { "sSettings_MenuBar_EnableMenuBarBlur", "Blur behind the Menu Bar (Windows 10 only)" },
            { "sSettings_MenuBar_EnableMenuBarMultiMon", "Show Menu Bar on multiple monitors" },
            { "sSettings_Desktop_EnableDesktop", "Enable Desktop" },
            { "sSettings_Desktop_DesktopHome", "Desktop home:" },
            { "sSettings_Desktop_LabelPosition", "Label position:" },
            { "sSettings_Desktop_LabelPositionRight", "Right" },
            { "sSettings_Desktop_LabelPositionBottom", "Bottom" },
            { "sSettings_Desktop_DynamicDesktop", "Dynamic Desktop" },
            { "sSettings_Desktop_EnableDynamicDesktop", "Show dynamic desktop navigation toolbar" },
            { "sSettings_Desktop_EnableDesktopOverlayHotKey", "Enable dynamic desktop overlay hotkey:" },
            { "sSettings_IconSize", "Icon size:" },
            { "sSettings_IconSizeLarge", "Large" },
            { "sSettings_IconSizeMedium", "Medium" },
            { "sSettings_IconSizeSmall", "Small" },
            { "sSettings_Taskbar_EnableTaskbar", "Enable Taskbar" },
            { "sSettings_Taskbar_TaskbarPosition", "Taskbar position:" },
            { "sSettings_Taskbar_PositionBottom", "Bottom" },
            { "sSettings_Taskbar_PositionTop", "Top" },
            { "sSettings_Taskbar_DisplayMode", "Display mode:" },
            { "sSettings_Taskbar_DisplayModeAppBar", "Taskbar reserves space" },
            { "sSettings_Taskbar_DisplayModeOverlap", "Taskbar overlaps windows" },
            { "sSettings_Taskbar_DisplayModeAutoHide", "Taskbar automatically hides" },
            { "sSettings_Taskbar_EnableTaskbarMultiMon", "Show Taskbar on multiple monitors" },
            { "sSettings_Advanced_Shell", "Shell" },
            { "sSettings_Advanced_CairoIsShell", "Cairo is currently set as your shell." },
            { "sSettings_Advanced_ExplorerIsShell", "Windows Explorer is currently set as your shell." },
            { "sSettings_Advanced_SetCairoAsShell", "Set Cairo as Shell" },
            { "sSettings_Advanced_SetExplorerAsShell", "Set Windows Explorer as Shell" },
            { "sSettings_Advanced_ShellChanged", "Shell settings have changed" },
            { "sSettings_Advanced_ShellChangedText", "You must log off for the changes to take effect." },
            { "sSettings_Advanced_LogOffNow", "Log Off Now" },
            { "sSettings_Advanced_LogOffLater", "Log Off Later" },
            { "sWelcome_StartTour", "Start Tour" },
            { "sWelcome_FinishTour", "Finish Tour" },
            { "sWelcome_Welcome", "Welcome to Cairo" },
            { "sWelcome_SelectLanguage", "Select a language:" },
            { "sWelcome_ChangingLanguage", "Changing language" },
            { "sWelcome_ChangingLanguageText", "Cairo will now restart to change the language." },
            { "sWelcome_MenuBar", "Menu Bar" },
            { "sWelcome_DynamicDesktop", "Dynamic Desktop" },
            { "sWelcome_Taskbar", "Taskbar" },
            { "sWelcome_MenuBarText", "Cairo's menu bar contains everything you need to take command of your computer." },
            { "sWelcome_MenuBarSec1Heading", "Cairo Menu" },
            { "sWelcome_MenuBarSec1Text", "Change settings, sign out, restart or shut down your computer, and other system tasks." },
            { "sWelcome_MenuBarSec2Heading", "Programs" },
            { "sWelcome_MenuBarSec2Text", "Launch and organize your applications. After this tour, the App Grabber will open, allowing you to choose apps to include and organize them into categories." },
            { "sWelcome_MenuBarSec3Heading", "Places" },
            { "sWelcome_MenuBarSec3Text", "Open important folders such as Documents, Downloads, Music, Pictures, This PC, and Recycle Bin." },
            { "sWelcome_MenuBarSec4Heading", "Stacks" },
            { "sWelcome_MenuBarSec4Text", "Drag any folder to the menu bar to create a stack for easy access." },
            { "sWelcome_MenuBarSec5Heading", "Notification Area" },
            { "sWelcome_MenuBarSec5Text", "Click the arrow to see your notification icons." },
            { "sWelcome_MenuBarSec6Heading", "Search" },
            { "sWelcome_MenuBarSec6Text", "Find files, folders, system settings, and more." },
            { "sWelcome_DesktopText", "Cairo's dynamic desktop transforms your desktop from a static workspace into an interactive file browser. Simply double-click a folder to navigate, or use the toolbar to browse." },
            { "sWelcome_DesktopSec1Heading", "Desktop Navigation Bar" },
            { "sWelcome_DesktopSec1Text", "Use the dynamic desktop toolbar to browse back or forward, go home, or pick a folder to view." },
            { "sWelcome_DesktopSec2Heading", "Dynamic Desktop Overlay" },
            { "sWelcome_DesktopSec2Text", "Activate the desktop overlay (press Win-Shift-D or click the desktop icon in the taskbar) to access your desktop without hiding or interrupting your work." },
            { "sWelcome_TaskbarText", "Cairo has replaced your taskbar with a smarter one that maximizes your productivity." },
            { "sWelcome_TaskbarSec1Heading", "Quick Launch Area" },
            { "sWelcome_TaskbarSec1Text", "Items pinned to your Windows taskbar were added to your Cairo quick launch. Drag programs in, or use the App Grabber to add more apps to quick launch." },
            { "sWelcome_TaskbarSec2Heading", "Categorized Windows" },
            { "sWelcome_TaskbarSec2Text", "Open windows in your taskbar are now organized the same way you choose to categorize your Programs menu. Now, all of your related tasks are grouped together for quick and easy use." },
            { "sWelcome_TaskbarSec3Heading", "Task List" },
            { "sWelcome_TaskbarSec3Text", "Lots of open windows? The task list shows your windows in a menu so that you can easily switch to the one you are looking for. You can also open the Windows 10 Task View from this menu." }
        };

        public static Dictionary<string, string> fr_FR = new Dictionary<string, string>
        {
            { "sProgramsMenu", "Applications" },
            { "sPlacesMenu", "Dossiers" },
            { "sCairoMenu_AboutCairo", "À propos de Cairo" },
            { "sCairoMenu_CheckForUpdates", "Rechercher des mises à jour" },
            { "sCairoMenu_CairoSettings", "Paramètres Cairo" },
            { "sCairoMenu_WindowsControlPanel", "Panneau de configuration Windows" },
            { "sCairoMenu_WindowsSettings", "Paramètres Windows" },
            { "sCairoMenu_Run", "Exécuter..." },
            { "sCairoMenu_TaskManager", "Gestionnaire de tâches" },
            { "sCairoMenu_ExitCairo", "Quitter Cairo..." },
            { "sCairoMenu_Sleep", "Mettre en veille" },
            { "sCairoMenu_Restart", "Redémarrer..." },
            { "sCairoMenu_ShutDown", "Arrêter..." },
            { "sCairoMenu_LogOff", "Se déconnecter..." },
            { "sAbout_Version", "Version" },
            { "sAbout_PreRelease", "Pré-version" },
            { "sAbout_Copyright", "Copyright © 2007-{0} Équipe de développement Cairo et contributeurs de la communauté.  Tous droits réservés." },
            { "sInterface_OK", "OK" },
            { "sInterface_Cancel", "Annuler" },
            { "sInterface_Continue", "Continuer" },
            { "sInterface_Finish", "Terminer" },
            { "sInterface_Yes", "Oui" },
            { "sInterface_No", "Non" },
            { "sInterface_Open", "Ouvrir" },
            { "sInterface_OpenWith", "Ouvrir avec..." },
            { "sInterface_OpenAsAdministrator", "Exécuter en tant qu'administrateur" },
            { "sInterface_RunAsUser", "Exécuter en tant qu'autre utilisateur" },
            { "sInterface_AddToStacks", "Ajouter aux piles" },
            { "sInterface_Copy", "Copier" },
            { "sInterface_Paste", "Coller" },
            { "sInterface_Delete", "Supprimer" },
            { "sInterface_Rename", "Renommer" },
            { "sInterface_Properties", "Propriétés" },
            { "sInterface_Browse", "Rechercher..." },
            { "sAppGrabber", "Sélecteur d'applications" },
            { "sAppGrabber_PleaseWait", "Veuillez patienter pendant que Cairo trouve vos applications..." },
            { "sAppGrabber_Page1Title", "Cairo a trouvé les applications suivantes installées sur votre ordinateur." },
            { "sAppGrabber_Page1Line1", "Veuillez glisser les applications que vous souhaitez que Cairo range dans le menu Applications à gauche.  Si vous souhaitez conserver les applications en dehors de ce menu, veuillez les glisser à droite." },
            { "sAppGrabber_Page1Line2", "Cairo a pré-sélectionné des applications qui pourraient être utiles pour votre menu Applications.  Pour ajouter ou supprimer des applications de ce menu à tout moment, lancez le sélecteur d'applications depuis le menu Cairo ou glissez simplement des éléments dans le menu." },
            { "sAppGrabber_ProgramsMenuItems", "Éléments du menu Applications" },
            { "sAppGrabber_InstalledApplications", "Applications installées" },
            { "sAppGrabber_Page2Title", "Catégories" },
            { "sAppGrabber_Page2Line1", "Les catégories vous permettent de grouper les applications par type afin qu'elles soient plus faciles à trouver. Une fois que vous avez terminé, vous pouvez ajouter, supprimer ou modifier les catégories et applications à travers le menu Applications lui-même. Pour plus de commodité, vous pouvez aussi lancer le sélecteur d'applications depuis le menu Cairo." },
            { "sAppGrabber_Page2Directions", "Instructions:" },
            { "sAppGrabber_Page2Directions1", "Glissez-déposez des applications dans les catégories que vous desirez." },
            { "sAppGrabber_Page2Directions2", "Cliquez sur le bouton plus pour ajouter une nouvelle catégorie." },
            { "sAppGrabber_Page2Directions3", "Cliquez le bouton X sur une catégorie pour la supprimer. (Les applications dans une catégorie supprimée deviendront non classées.)" },
            { "sAppGrabber_Page2Directions4", "Clic droit sur une catégorie pour la renommer." },
            { "sAppGrabber_Page2Directions5", "Cliquez sur le bouton \"Replier\" pour afficher uniquement les applications qui nécessitent d'être classées." },
            { "sAppGrabber_Page2Directions6", "Les éléments placés dans la catégorie Lancement rapide vont apparaître dans la zone de lancement rapide de la barre de tâches de Cairo. Les éléments placés ici ne seront pas supprimés du menu Applications.  Pour supprimer un élément, glissez-le en dehors de la catégorie Lancement rapide." },
            { "sAppGrabber_ProgramCategories", "Catégories d'applications" },
            { "sAppGrabber_Hide", "Replier" },
            { "sAppGrabber_QuickLaunch", "Lancement rapide" },
            { "sAppGrabber_Uncategorized", "Non classé" },
            { "sAppGrabber_All", "Tous" },
            { "sAppGrabber_Untitled", "Sans titre" },
            { "sAppGrabber_Category_Accessories", "Accessoires" },
            { "sAppGrabber_Category_Productivity", "Productivité" },
            { "sAppGrabber_Category_Development", "Développement" },
            { "sAppGrabber_Category_Graphics", "Graphisme" },
            { "sAppGrabber_Category_Media", "Média" },
            { "sAppGrabber_Category_Internet", "Internet" },
            { "sAppGrabber_Category_Games", "Jeux" },
            { "sRun_Title", "Exécuter" },
            { "sRun_Info", "Tapez le nom d'une application, d'un dossier, d'un document ou d'une ressource Internet, et Cairo l'ouvrira pour vous." },
            { "sExitCairo_Title", "Êtes-vous sûr de vouloir quitter Cairo ?" },
            { "sExitCairo_Info", "Vous devrez redémarrer ou utiliser le raccourci du menu démarrer afin de lancer Cairo à nouveau." },
            { "sExitCairo_ExitCairo", "Quitter Cairo" },
            { "sLogoff_Title", "Êtes-vous sûr de vouloir vous déconnecter maintenant ?" },
            { "sLogoff_Info", "Vous allez perdre tous les documents non sauvegardés et être déconnecté." },
            { "sLogoff_Logoff", "Se déconnecter" },
            { "sRestart_Title", "Êtes-vous sûr de vouloir redémarrer maintenant ?" },
            { "sRestart_Info", "Vous allez perdre tous les documents non sauvegardés et votre ordinateur va redémarrer." },
            { "sRestart_Restart", "Redémarrer" },
            { "sShutDown_Title", "Êtes-vous sûr de vouloir arrêter l'ordinateur maintenant ?" },
            { "sShutDown_Info", "Vous allez perdre tous les documents non sauvegardés et votre ordinateur va s'arrêter." },
            { "sShutDown_ShutDown", "Arrêter" },
            { "sProgramsMenu_Empty", "Aucune application n'a encore été sélectionnée. Ouvrez le sélecteur d'applications pour commencer !" },
            { "sProgramsMenu_UninstallAProgram", "Désinstaller une application" },
            { "sProgramsMenu_RemoveFromMenu", "Supprimer de la liste" },
            { "sProgramsMenu_RemoveTitle", "Supprimer cette application de la liste ?" },
            { "sProgramsMenu_RemoveInfo", "\"{0}\" va être supprimé de la liste {1}. Cela ne désinstallera pas l'application." },
            { "sProgramsMenu_AlwaysAdminTitle", "Toujours exécuter cette application en tant qu'administrateur ?" },
            { "sProgramsMenu_AlwaysAdminInfo", "Vous avez précédemment exécuté \"{0}\" en tant qu'administrateur. Souhaitez-vous que Cairo l'exécute automatiquement en tant qu'administrateur à chaque fois ?" },
            { "sProgramsMenu_Remove", "Supprimer" },
            { "sProgramsMenu_UWPInfo", "C'est une application universelle (UWP)." },
            { "sProgramsMenu_AddToQuickLaunch", "Ajouter au lancement rapide" },
            { "sPlacesMenu_Documents", "Documents" },
            { "sPlacesMenu_Downloads", "Téléchargements" },
            { "sPlacesMenu_Music", "Musique" },
            { "sPlacesMenu_Pictures", "Images" },
            { "sPlacesMenu_Videos", "Vidéos" },
            { "sPlacesMenu_ThisPC", "Ce PC" },
            { "sPlacesMenu_ProgramFiles", "Program Files" },
            { "sPlacesMenu_RecycleBin", "Corbeille" },
            { "sStacks_Tooltip", "Glissez des répertoires ici pour un accès facile." },
            { "sStacks_OpenInNewWindow", "Ouvrir dans une nouvelle fenêtre" },
            { "sStacks_Remove", "Supprimer" },
            { "sStacks_Empty", "Ce répertoire est vide." },
            { "sMenuBar_OpenDateTimeSettings", "Ouvrir les paramètres de date et heure" },
            { "sMenuBar_OpenActionCenter", "Ouvrir le centre de notifications" },
            { "sMenuBar_ToggleNotificationArea", "Afficher/masquer les icônes de la zone de notification" },
            { "sMenuBar_Volume", "Volume" },
            { "sMenuBar_OpenSoundSettings", "Ouvrir les paramètres de son" },
            { "sSearch_Title", "Rechercher sur le bureau" },
            { "sSearch_ViewAllResults", "Voir tous les résultats" },
            { "sSearch_LastModified", "Modifié le : {0}" },
            { "sSearch_Error", "Nous n'avons pas pu ouvrir le résultat de la recherche." },
            { "sDesktop_Personalize", "Personnaliser" },
            { "sDesktop_DeleteTitle", "Êtes-vous sûr de vouloir supprimer ceci ?" },
            { "sDesktop_DeleteInfo", "\"{0}\" va être envoyé à la corbeille." },
            { "sDesktop_BrowseTitle", "Choisissez un dossier à afficher en tant que votre bureau :" },
            { "sDesktop_CurrentFolder", "Dossier actuel :" },
            { "sDesktop_Back", "Retour" },
            { "sDesktop_Forward", "Avancer" },
            { "sDesktop_Browse", "Choisir un dossier" },
            { "sDesktop_Home", "Accueil" },
            { "sTaskbar_Empty", "Ouvrez des fenêtres pour les voir listées ici." },
            { "sTaskbar_Minimize", "Réduire" },
            { "sTaskbar_Restore", "Agrandir" },
            { "sTaskbar_Close", "Fermer" },
            { "sTaskbar_TaskView", "Affichage des tâches" },
            { "sTaskbar_TaskListToolTip", "Liste des tâches" },
            { "sTaskbar_DesktopOverlayToolTip", "Bureau en superposition" },
            { "sError_OhNo", "Oups !" },
            { "sError_FileNotFoundInfo", "L'élément n'a pas pu être ouvert parce qu'il n'existe pas ou Cairo n'a pas la permission de l'ouvrir." },
            { "sError_CantOpenAppWiz", "Impossible d'ouvrir le panneau Programmes et fonctionnalités." },
            { "sSettings_General", "Général" },
            { "sSettings_MenuBar", "Barre de menu" },
            { "sSettings_Desktop", "Bureau" },
            { "sSettings_Taskbar", "Barre des tâches" },
            { "sSettings_Appearance", "Apparence" },
            { "sSettings_Advanced", "Avancé" },
            { "sSettings_Default", "Par défaut" },
            { "sSettings_RestartCairo", "Redémarrer Cairo pour appliquer" },
            { "sSettings_Restarting", "Redémarrage en cours..." },
            { "sSettings_General_UpdateCheck", "Rechercher automatiquement les mises à jour" },
            { "sSettings_General_Language", "Langue :" },
            { "sSettings_General_Theme", "Thème :" },
            { "sSettings_General_ThemeTooltip", "Placez les thèmes dans votre répertoire d'installation Cairo." },
            { "sSettings_General_TimeFormat", "Format de l'heure :" },
            { "sSettings_General_TimeFormatTooltip", "Voici quelques valeurs que vous pouvez utiliser ici :\r\nd	Jour du mois\r\nddd	Jour de la semaine\r\nh	Heure (12 heures)\r\nhh	Heure (12 heures, précédée d'un zéro)\r\nH	Heure (24 jeures)\r\nHH	Heure (24 heures, précédée d'un zéro)\r\nm	Minutes\r\nmm	Minutes (précédées d'un zéro)\r\ns	Secondes\r\nss	Secondes (précédées d'un zéro)\r\ntt	AM/PM le cas échéant" },
            { "sSettings_General_DateFormat", "Format de la date :" },
            { "sSettings_General_DateFormatTooltip", "Voici quelques valeurs que vous pouvez utiliser ici :\r\nd	Jour du mois\r\ndd	Jour du mois (précédé d'un zéro)\r\nddd	Jour de la semaine (abrégé)\r\ndddd	Jour de la semaine (texte)\r\nM	Mois\r\nMM	Mois (précédé d'un zéro)\r\nMMM	Mois (abrégé)\r\nMMMM	Mois (texte)\r\nyy	Année (2 chiffres)\r\nyyyy	Année (4 chiffres)" },
            { "sSettings_General_FilesAndFolders", "Fichiers et dossiers" },
            { "sSettings_General_ShowSubDirectories", "Afficher les sous-répertoires" },
            { "sSettings_General_ShowFileExtensions", "Afficher les extensions des fichiers" },
            { "sSettings_General_ForceSoftwareRendering", "Forcer le rendu logiciel" },
            { "sSettings_General_FileManager", "Gestionnaire de fichiers :" },
            { "sSettings_General_FoldersOpenDesktopOverlay", "Les dossiers s'ouvrent en utilisant le bureau dynamique en superposition" },
            { "sSettings_MenuBar_DefaultProgramsCategory", "Catégorie de programmes par défaut :" },
            { "sSettings_MenuBar_EnableMenuBarShadow", "Activer l'ombre de la barre de menu" },
            { "sSettings_MenuBar_NotificationArea", "Zone de notification" },
            { "sSettings_MenuBar_EnableNotificationArea", "Activer la zone de notification" },
            { "sSettings_MenuBar_NotificationAreaError", "Le composent de la zone de notification n'a pas pu être chargé. Veuillez installer le redistribuable Microsoft Visual C++ 2015." },
            { "sSettings_MenuBar_ShowNotifyIcons", "Afficher les icônes de la zone de notification :" },
            { "sSettings_MenuBar_ShowNotifyIconsCollapsed", "Repliées" },
            { "sSettings_MenuBar_ShowNotifyIconsAlways", "Toujours" },
            { "sSettings_MenuBar_EnableCairoMenuHotKey", "Activer le raccourci clavier du menu Cairo :" },
            { "sSettings_MenuBar_EnableMenuBarBlur", "Flou sous la barre de menu (Windows 10 uniquement)" },
            { "sSettings_MenuBar_EnableMenuBarMultiMon", "Afficher la barre de menu sur des affichages multiples" },
            { "sSettings_Desktop_EnableDesktop", "Activer le bureau" },
            { "sSettings_Desktop_DesktopHome", "Accueil du bureau :" },
            { "sSettings_Desktop_LabelPosition", "Position de l'étiquette :" },
            { "sSettings_Desktop_LabelPositionRight", "Droite" },
            { "sSettings_Desktop_LabelPositionBottom", "Bas" },
            { "sSettings_Desktop_DynamicDesktop", "Bureau dynamique" },
            { "sSettings_Desktop_EnableDynamicDesktop", "Afficher la barre d'outils de navigation du bureau dynamique" },
            { "sSettings_Desktop_EnableDesktopOverlayHotKey", "Activer le raccourci clavier du bureau dynamique en superposition :" },
            { "sSettings_IconSize", "Taille des icônes :" },
            { "sSettings_IconSizeLarge", "Grand" },
            { "sSettings_IconSizeMedium", "Moyen" },
            { "sSettings_IconSizeSmall", "Petit" },
            { "sSettings_Taskbar_EnableTaskbar", "Activer la barre des tâches" },
            { "sSettings_Taskbar_TaskbarPosition", "Position de la barre des tâches :" },
            { "sSettings_Taskbar_PositionBottom", "Bas" },
            { "sSettings_Taskbar_PositionTop", "Haut" },
            { "sSettings_Taskbar_DisplayMode", "Mode d'affichage :" },
            { "sSettings_Taskbar_DisplayModeAppBar", "La barre des tâches réserve l'espace" },
            { "sSettings_Taskbar_DisplayModeOverlap", "La barre des tâches chevauche les fenêtres" },
            { "sSettings_Taskbar_DisplayModeAutoHide", "La barre des tâches est masquée automatiquement" },
            { "sSettings_Taskbar_EnableTaskbarMultiMon", "Afficher la barre des tâches sur des affichages multiples" },
            { "sSettings_Advanced_Shell", "Shell" },
            { "sSettings_Advanced_CairoIsShell", "Cairo est actuellement défini comme votre shell." },
            { "sSettings_Advanced_ExplorerIsShell", "L'explorateur Windows est actuellement défini comme votre shell." },
            { "sSettings_Advanced_SetCairoAsShell", "Définir Cairo comme Shell" },
            { "sSettings_Advanced_SetExplorerAsShell", "Définir l'explorateur Windows comme Shell" },
            { "sSettings_Advanced_ShellChanged", "Les paramètres du Shell ont changé" },
            { "sSettings_Advanced_ShellChangedText", "Vous devez vous déconnecter pour que les changements prennent effet." },
            { "sSettings_Advanced_LogOffNow", "Se déconnecter maintenant" },
            { "sSettings_Advanced_LogOffLater", "Se déconnecter ultérieurement" },
            { "sWelcome_StartTour", "Commencer la visite" },
            { "sWelcome_FinishTour", "Terminer la visite" },
            { "sWelcome_Welcome", "Bienvenue dans Cairo" },
            { "sWelcome_SelectLanguage", "Selectionnez une langue :" },
            { "sWelcome_ChangingLanguage", "Changer de langue" },
            { "sWelcome_ChangingLanguageText", "Cairo va maintenant redémarrer pour changer la langue." },
            { "sWelcome_MenuBar", "Barre de menu" },
            { "sWelcome_DynamicDesktop", "Bureau dynamique" },
            { "sWelcome_Taskbar", "Barre des tâches" },
            { "sWelcome_MenuBarText", "La barre de menu Cairo contient tout ce dont vous avez besoin pour prendre en main votre ordinateur." },
            { "sWelcome_MenuBarSec1Heading", "Menu Cairo" },
            { "sWelcome_MenuBarSec1Text", "Changer des paramètres, se déconnecter, redémarrer ou arrêter votre ordinateur, et autres tâches système." },
            { "sWelcome_MenuBarSec2Heading", "Applications" },
            { "sWelcome_MenuBarSec2Text", "Lancer et organiser vos applications. Après cette visite, le sélecteur d'applications s'ouvrira pour vous permettre de choisir les applications à inclure et les organiser en catégories." },
            { "sWelcome_MenuBarSec3Heading", "Dossiers" },
            { "sWelcome_MenuBarSec3Text", "Ouvrir des dossiers importants tels que Documents, Téléchargements, Musique, Images, Ce PC et la Corbeille." },
            { "sWelcome_MenuBarSec4Heading", "Piles" },
            { "sWelcome_MenuBarSec4Text", "Glisser n'importe quel dossier vers la barre de menu afin de créer une pile pour un accès facile." },
            { "sWelcome_MenuBarSec5Heading", "Zone de notification" },
            { "sWelcome_MenuBarSec5Text", "Cliquer sur la flèche pour voir vos icônes de notification." },
            { "sWelcome_MenuBarSec6Heading", "Rechercher" },
            { "sWelcome_MenuBarSec6Text", "Trouver des fichiers, dossiers, paramètres système, et plus encore." },
            { "sWelcome_DesktopText", "Le bureau dynamique Cairo transforme votre bureau qui était un espace de travail statique en un explorateur de fichiers interactif. Faites simplement un double clic sur un dossier pour naviguer, ou utilisez la barre d'outils pour le parcourir." },
            { "sWelcome_DesktopSec1Heading", "Barre de navigation du bureau" },
            { "sWelcome_DesktopSec1Text", "Utilisez la barre d'outils du bureau dynamique pour reculer ou avancer, retourner à l'accueil, ou choisir un dossier à afficher." },
            { "sWelcome_DesktopSec2Heading", "Bureau dynamique en superposition" },
            { "sWelcome_DesktopSec2Text", "Activez le bureau en superposition (Appuyez sur Win-Shift-D ou cliquez sur l'icône du bureau dans la barre des tâches) pour accéder à votre bureau sans cacher ou interrompre votre travail." },
            { "sWelcome_TaskbarText", "Cairo a remplacé votre barre des tâches par une autre plus intelligente qui maximise votre productivité." },
            { "sWelcome_TaskbarSec1Heading", "Zone de lancement rapide" },
            { "sWelcome_TaskbarSec1Text", "Les éléments épinglés à votre barre des tâches Windows ont été ajoutés au lancement rapide de votre Cairo. Glissez-y des applications, ou utilisez le sélecteur d'applications pour ajouter d'avantage d'applications au lancement rapide." },
            { "sWelcome_TaskbarSec2Heading", "Fenêtres classées" },
            { "sWelcome_TaskbarSec2Text", "Les fenêtres ouvertes dans votre barre des tâches sont maintenant organisées de la même façon que celle que vous avez choisie pour classer votre menu Applications. Maintenant, toutes vos tâches connexes sont regroupées ensemble pour une utilisation rapide et facile." },
            { "sWelcome_TaskbarSec3Heading", "Liste des tâches" },
            { "sWelcome_TaskbarSec3Text", "Beaucoup de fenêtres ouvertes ? La liste des tâches montre vos fenêtres dans un menu afin de vous permettre de basculer facilement vers celle que vous recherchez. Vous pouvez aussi ouvrir l'affichage des tâches de Windows 10 depuis ce menu." }
        };

        public static Dictionary<string, string> zh_CN = new Dictionary<string, string>
        {
            { "sProgramsMenu", "程序" },
            { "sPlacesMenu", "我的电脑" },
            { "sCairoMenu_AboutCairo", "About Cairo" },
            { "sCairoMenu_CheckForUpdates", "检查更新" },
            { "sCairoMenu_CairoSettings", "Cairo 设置" },
            { "sCairoMenu_WindowsControlPanel", "Windows控制面板" },
            { "sCairoMenu_WindowsSettings", "Windows 设置" },
            { "sCairoMenu_Run", "运行..." },
            { "sCairoMenu_TaskManager", "任务管理器" },
            { "sCairoMenu_ExitCairo", "退出 Cairo..." },
            { "sCairoMenu_Sleep", "睡眠" },
            { "sCairoMenu_Restart", "重启..." },
            { "sCairoMenu_ShutDown", "关机..." },
            { "sCairoMenu_LogOff", "注销..." },
            { "sAbout_Version", "版本" },
            { "sAbout_PreRelease", "Pre-release" },
            { "sAbout_Copyright", "Copyright © 2007-{0} Cairo 开发团队和社区贡献者。保留所有权利." },
            { "sInterface_OK", "确认" },
            { "sInterface_Cancel", "取消" },
            { "sInterface_Continue", "继续" },
            { "sInterface_Finish", "完成" },
            { "sInterface_Yes", "是" },
            { "sInterface_No", "否" },
            { "sInterface_Open", "打开" },
            { "sInterface_OpenWith", "打开方式..." },
            { "sInterface_OpenAsAdministrator", "管理员身份运行" },
            { "sInterface_AddToStacks", "添加到任务栏" },
            { "sInterface_Copy", "复制" },
            { "sInterface_Paste", "粘贴" },
            { "sInterface_Delete", "删除" },
            { "sInterface_Rename", "重命名" },
            { "sInterface_Properties", "属性" },
            { "sInterface_Browse", "浏览..." },
            { "sAppGrabber", "App Grabber" },
            { "sAppGrabber_PleaseWait", "请稍候，Cairo正在查找你的应用程序。" },
            { "sAppGrabber_Page1Title", "Cairo已经在您的计算机上安装了以下应用程序。." },
            { "sAppGrabber_Page1Line1", "请将您想要Cairo的应用程序拖到左边的程序菜单中。如果您想要将应用程序从这个菜单中删除，请将它们拖到右边。" },
            { "sAppGrabber_Page1Line2", "Cairo有预先选择的应用程序，可能对您的程序菜单有用。要在任何时候添加或删除此菜单中的应用程序，请从Cairo菜单中运行App Grabber，或者简单地将项目拖放到菜单中。" },
            { "sAppGrabber_ProgramsMenuItems", "程序菜单" },
            { "sAppGrabber_InstalledApplications", "已安装的应用程序" },
            { "sAppGrabber_Page2Title", "类别" },
            { "sAppGrabber_Page2Line1", "类别允许您按类型分组应用程序，以便更容易找到它们。完成之后，可以通过程序菜单本身添加、删除或编辑类别和应用程序。为了方便起见，您还可以从Cairo菜单中运行App Grabber。" },
            { "sAppGrabber_Page2Directions", "方向:" },
            { "sAppGrabber_Page2Directions1", "将应用程序拖放到您想要的类别中。" },
            { "sAppGrabber_Page2Directions2", "单击+按钮添加一个新类别。" },
            { "sAppGrabber_Page2Directions3", "单击类别中的X按钮删除它。(被删除的类别中的应用程序将会被分类。)" },
            { "sAppGrabber_Page2Directions4", "右键单击一个类别来重命名它。" },
            { "sAppGrabber_Page2Directions5", "单击/“隐藏/”按钮只显示需要分类的应用程序。" },
            { "sAppGrabber_Page2Directions6", "在快速发射类别中放置的物品将出现在开罗任务栏的快速发射区。此处放置的项目不会从程序菜单中删除。要删除一个项目，从快速启动类别中拖出一个项目。" },
            { "sAppGrabber_ProgramCategories", "项目类别" },
            { "sAppGrabber_Hide", "隐藏" },
            { "sAppGrabber_QuickLaunch", "快速启动" },
            { "sAppGrabber_Uncategorized", "未分类的" },
            { "sAppGrabber_All", "所有" },
            { "sAppGrabber_Untitled", "记事本" },
            { "sAppGrabber_Category_Accessories", "附件" },
            { "sAppGrabber_Category_Productivity", "计算器" },
            { "sAppGrabber_Category_Development", "数字输入画板" },
            { "sAppGrabber_Category_Graphics", "画图" },
            { "sAppGrabber_Category_Games", "游戏" },
            { "sRun_Title", "开始" },
            { "sRun_Info", "键入程序、文件夹、文档或Internet资源的名称，Cairo将为您打开它。" },
            { "sExitCairo_Title", "你确定要离开Cairo吗?" },
            { "sExitCairo_Info", "为了再次运行Cairo，您需要重新启动或使用开始菜单快捷方式。" },
            { "sExitCairo_ExitCairo", "退出 Cairo" },
            { "sLogoff_Title", "你确定你现在要注销吗?" },
            { "sLogoff_Info", "您将丢失所有未保存的文档并注销。" },
            { "sLogoff_Logoff", "注销" },
            { "sRestart_Title", "您确定要重新启动吗?" },
            { "sRestart_Info", "您将丢失所有未保存的文档，您的计算机将重新启动。" },
            { "sRestart_Restart", "重新启动" },
            { "sShutDown_Title", "你确定你现在要关机吗?" },
            { "sShutDown_Info", "您将丢失所有未保存的文档，您的计算机将关闭。" },
            { "sShutDown_ShutDown", "关闭" },
            { "sProgramsMenu_Empty", "目前还没有选定任何程序。打开App Grabber开始!" },
            { "sProgramsMenu_UninstallAProgram", "卸载程序" },
            { "sProgramsMenu_RemoveFromMenu", "从列表中删除" },
            { "sProgramsMenu_RemoveTitle", "从列表中删除这个应用程序?" },
            { "sProgramsMenu_RemoveInfo", "\"{0}\" 将从 {1} 列表中删除。这不会卸载程序。" },
            { "sProgramsMenu_AlwaysAdminTitle", "总是以管理员身份运行吗?" },
            { "sProgramsMenu_AlwaysAdminInfo", "您以前作为管理员运行 \"{0}\" 。您希望Cairo每次都自动运行它作为管理员吗?" },
            { "sProgramsMenu_Remove", "删除" },
            { "sProgramsMenu_UWPInfo", "这是一个通用的Windows平台(UWP)应用程序。" },
            { "sProgramsMenu_AddToQuickLaunch", "添加到快速启动" },
            { "sPlacesMenu_Documents", "文档" },
            { "sPlacesMenu_Downloads", "下载" },
            { "sPlacesMenu_Music", "音乐" },
            { "sPlacesMenu_Pictures", "图片" },
            { "sPlacesMenu_Videos", "视频" },
            { "sPlacesMenu_ThisPC", "我的电脑" },
            { "sPlacesMenu_ProgramFiles", "程序文件" },
            { "sPlacesMenu_RecycleBin", "回收站" },
            { "sStacks_Tooltip", "将目录拖到这里便于访问。" },
            { "sStacks_OpenInNewWindow", "在新窗口打开" },
            { "sStacks_Remove", "删除" },
            { "sStacks_Empty", "这个文件夹是空的。" },
            { "sMenuBar_OpenDateTimeSettings", "打开日期和时间设置" },
            { "sMenuBar_OpenActionCenter", "打开通知中心" },
            { "sMenuBar_ToggleNotificationArea", "切换通知区域图标" },
            { "sSearch_Title", "桌面搜索" },
            { "sSearch_ViewAllResults", "查看所有的结果" },
            { "sSearch_LastModified", "最后修改: {0}" },
            { "sSearch_Error", "我们无法打开搜索结果。" },
            { "sDesktop_Personalize", "个性化" },
            { "sDesktop_DeleteTitle", "您确定要删除这个吗？" },
            { "sDesktop_DeleteInfo", "\"{0}\" 将被发送到回收站。" },
            { "sDesktop_BrowseTitle", "选择要显示为桌面的文件夹:" },
            { "sTaskbar_Empty", "打开窗口，看看它们在这里列出。" },
            { "sTaskbar_Minimize", "最小化" },
            { "sTaskbar_Restore", "恢复" },
            { "sTaskbar_Close", "关闭" },
            { "sTaskbar_TaskView", "任务管理器" },
            { "sTaskbar_TaskListToolTip", "任务列表" },
            { "sTaskbar_DesktopOverlayToolTip", "桌面覆盖" },
            { "sError_OhNo", "哦!" },
            { "sError_FileNotFoundInfo", "该项目不能被打开，因为它不存在，或者Cairo没有开放的许可。" },
            { "sError_CantOpenAppWiz", "无法打开程序和功能控制面板。" },
            { "sSettings_General", "一般" },
            { "sSettings_MenuBar", "菜单栏" },
            { "sSettings_Desktop", "桌面" },
            { "sSettings_Taskbar", "任务栏" },
            { "sSettings_Appearance", "外观" },
            { "sSettings_Advanced", "优先" },
            { "sSettings_Default", "默认" },
            { "sSettings_RestartCairo", "Cairo重启应用" },
            { "sSettings_Restarting", "重新启动..." },
            { "sSettings_General_UpdateCheck", "自动检查更新" },
            { "sSettings_General_Language", "语言:" },
            { "sSettings_General_Theme", "主题:" },
            { "sSettings_General_ThemeTooltip", "将主题放置到Cairo安装目录中。" },
            { "sSettings_General_TimeFormat", "时间格式:" },
            { "sSettings_General_TimeFormatTooltip", "你可以在这里使用的一些值:\r\nd	月日(12小时)\r\nh小时(12小时，前导零)\r\nh小时(24小时，前导零)\r\n mm分钟(前导零)\r\n 秒(领先零)\r\n秒(前导零)\r\n，如果适用。" },
            { "sSettings_General_DateFormat", "日期格式:" },
            { "sSettings_General_DateFormatTooltip", "一些值，你可以使用这里：\r\n D天月\r\n DD天月（前导零）\r \n ddd周日（略）\r\n dddd周日（文本）\r\n m月\r\n毫米月（前导零）\r\n MMM月（略）\r\n mmmm月（文本）\r\n YY年（段）\r\n YYYY年（4）" },
            { "sSettings_General_FilesAndFolders", "文件和文件夹" },
            { "sSettings_General_ShowSubDirectories", "显示子目录" },
            { "sSettings_General_ShowFileExtensions", "显示文件扩展名" },
            { "sSettings_General_ForceSoftwareRendering", "软件渲染" },
            { "sSettings_General_FileManager", "文件管理器:" },
            { "sSettings_General_FoldersOpenDesktopOverlay", "文件夹打开使用桌面覆盖。" },
            { "sSettings_MenuBar_DefaultProgramsCategory", "默认的项目类别:" },
            { "sSettings_MenuBar_EnableMenuBarShadow", "启用菜单栏阴影" },
            { "sSettings_MenuBar_NotificationArea", "通知区域" },
            { "sSettings_MenuBar_EnableNotificationArea", "启用通知区域" },
            { "sSettings_MenuBar_NotificationAreaError", "无法加载通知区域组件。请安装微软Visual C++ 2015可再发行。" },
            { "sSettings_MenuBar_ShowNotifyIcons", "显示通知区域图标:" },
            { "sSettings_MenuBar_ShowNotifyIconsCollapsed", "折叠" },
            { "sSettings_MenuBar_ShowNotifyIconsAlways", "总是" },
            { "sSettings_MenuBar_EnableCairoMenuHotKey", "启用菜单热键 Cairo:" },
            { "sSettings_MenuBar_EnableMenuBarBlur", "在菜单栏后面模糊（只有Windows 10）" },
            { "sSettings_MenuBar_EnableMenuBarMultiMon", "在多个监视器上显示菜单栏" },
            { "sSettings_Desktop_EnableDesktop", "使桌面" },
            { "sSettings_Desktop_DesktopHome", "桌面:" },
            { "sSettings_Desktop_LabelPosition", "标签的位置:" },
            { "sSettings_Desktop_LabelPositionRight", "右侧" },
            { "sSettings_Desktop_LabelPositionBottom", "底部" },
            { "sSettings_Desktop_DynamicDesktop", "动态桌面" },
            { "sSettings_Desktop_EnableDynamicDesktop", "使用动态桌面" },
            { "sSettings_Desktop_EnableDesktopOverlayHotKey", "启用桌面叠加热键:" },
            { "sSettings_IconSize", "图标大小:" },
            { "sSettings_IconSizeLarge", "大" },
            { "sSettings_IconSizeMedium", "普通的" },
            { "sSettings_IconSizeSmall", "小" },
            { "sSettings_Taskbar_EnableTaskbar", "任务栏" },
            { "sSettings_Taskbar_TaskbarPosition", "任务栏的位置:" },
            { "sSettings_Taskbar_PositionBottom", "底部" },
            { "sSettings_Taskbar_PositionTop", "顶部" },
            { "sSettings_Taskbar_DisplayMode", "显示模式:" },
            { "sSettings_Taskbar_DisplayModeAppBar", "任务栏保留空间" },
            { "sSettings_Taskbar_DisplayModeOverlap", "任务栏重叠窗口" },
            { "sSettings_Taskbar_DisplayModeAutoHide", "任务栏自动隐藏" },
            { "sSettings_Taskbar_EnableTaskbarMultiMon", "在多个监视器上显示任务栏。" },
            { "sSettings_Advanced_Shell", "壳" },
            { "sSettings_Advanced_CairoIsShell", "Cairo 当前设置为您的shell吗?" },
            { "sSettings_Advanced_ExplorerIsShell", "Windows资源管理器当前设置为您的shell。" },
            { "sSettings_Advanced_SetCairoAsShell", "Cairo设置为壳" },
            { "sSettings_Advanced_SetExplorerAsShell", "将Windows资源管理器设置为Shell。" },
            { "sSettings_Advanced_ShellChanged", "外壳设置已经改变" },
            { "sSettings_Advanced_ShellChangedText", "您必须注销，以便更改生效。" },
            { "sSettings_Advanced_LogOffNow", "现在注销" },
            { "sSettings_Advanced_LogOffLater", "稍后注销" },
            { "sWelcome_StartTour", "开始运行" },
            { "sWelcome_FinishTour", "结束运行" },
            { "sWelcome_Welcome", "欢迎来到Cairo" },
            { "sWelcome_SelectLanguage", "选择一种语言:" },
            { "sWelcome_ChangingLanguage", "改变语言" },
            { "sWelcome_ChangingLanguageText", "Cairo现在将重新开始改变这种语言。" },
            { "sWelcome_MenuBar", "菜单栏" },
            { "sWelcome_DynamicDesktop", "动态桌面" },
            { "sWelcome_Taskbar", "任务栏" },
            { "sWelcome_MenuBarText", "Cairo'菜单栏包含了所有你需要掌握的电脑指令。" },
            { "sWelcome_MenuBarSec1Heading", "Cairo 菜单" },
            { "sWelcome_MenuBarSec1Text", "更改设置、签名、重新启动或关闭计算机，以及其他系统任务。" },
            { "sWelcome_MenuBarSec2Heading", "项目" },
            { "sWelcome_MenuBarSec2Text", "启动和组织你的应用程序。在这次旅行之后，App Grabber将会开放，允许你选择应用程序，并将它们分类。" },
            { "sWelcome_MenuBarSec3Heading", "位置" },
            { "sWelcome_MenuBarSec3Text", "打开重要文件夹，如文档、下载、音乐、图片、这台PC和Recycle Bin。" },
            { "sWelcome_MenuBarSec4Heading", "进程应用" },
            { "sWelcome_MenuBarSec4Text", "将任何文件夹拖到菜单栏中，创建一个堆栈，以方便访问。" },
            { "sWelcome_MenuBarSec5Heading", "通知区域" },
            { "sWelcome_MenuBarSec5Text", "单击箭头以查看通知图标。" },
            { "sWelcome_MenuBarSec6Heading", "搜索" },
            { "sWelcome_MenuBarSec6Text", "查找文件、文件夹、系统设置等。" },
            { "sWelcome_DesktopText", "Cairo的动态桌面将桌面从静态工作区转换为交互式文件浏览器。只需双击一个文件夹来导航，或者使用工具栏来浏览。" },
            { "sWelcome_DesktopSec1Heading", "桌面导航栏" },
            { "sWelcome_DesktopSec1Text", "使用动态桌面工具栏浏览或前进，回家，或选择一个文件夹查看。" },
            { "sWelcome_DesktopSec2Heading", "动态桌面覆盖" },
            { "sWelcome_DesktopSec2Text", "激活桌面覆盖(按“按”按钮或单击“任务栏”中的桌面图标)来访问你的桌面，而不需要隐藏或打断你的工作。" },
            { "sWelcome_TaskbarText", "Cairo 已经取代了你的任务栏，让你的工作效率最大化。" },
            { "sWelcome_TaskbarSec1Heading", "快速启动区" },
            { "sWelcome_TaskbarSec1Text", "你的Windows任务栏上的条目被添加到你的Cairo快速启动中。拖动程序，或者使用App Grabber来添加更多的应用程序来快速启动。" },
            { "sWelcome_TaskbarSec2Heading", "分类窗口" },
            { "sWelcome_TaskbarSec2Text", "你的任务栏中打开的窗口和你选择分类你的程序菜单的方式是一样的。现在，所有相关的任务都被分组在一起，以便快速和轻松地使用。" },
            { "sWelcome_TaskbarSec3Heading", "任务列表" },
            { "sWelcome_TaskbarSec3Text", "很多敞开的窗户吗?任务列表在菜单中显示你的窗口，这样你就可以轻松切换到你要找的那个。您也可以从这个菜单打开Windows 10任务视图。" }
        };
    }
}
