//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CairoDesktop.Configuration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDesktop {
            get {
                return ((bool)(this["EnableDesktop"]));
            }
            set {
                this["EnableDesktop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableTaskbar {
            get {
                return ((bool)(this["EnableTaskbar"]));
            }
            set {
                this["EnableTaskbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMenuBarShadow {
            get {
                return ((bool)(this["EnableMenuBarShadow"]));
            }
            set {
                this["EnableMenuBarShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstRun {
            get {
                return ((bool)(this["IsFirstRun"]));
            }
            set {
                this["IsFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeFormat {
            get {
                return ((string)(this["TimeFormat"]));
            }
            set {
                this["TimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string DateFormat {
            get {
                return ((string)(this["DateFormat"]));
            }
            set {
                this["DateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%WINDIR%\\explorer.exe")]
        public string FileManager {
            get {
                return ((string)(this["FileManager"]));
            }
            set {
                this["FileManager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableSysTray {
            get {
                return ((bool)(this["EnableSysTray"]));
            }
            set {
                this["EnableSysTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDynamicDesktop {
            get {
                return ((bool)(this["EnableDynamicDesktop"]));
            }
            set {
                this["EnableDynamicDesktop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string CairoTheme {
            get {
                return ((string)(this["CairoTheme"]));
            }
            set {
                this["CairoTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DesktopDirectory {
            get {
                return ((string)(this["DesktopDirectory"]));
            }
            set {
                this["DesktopDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TaskbarMode {
            get {
                return ((int)(this["TaskbarMode"]));
            }
            set {
                this["TaskbarMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysTrayAlwaysExpanded {
            get {
                return ((bool)(this["SysTrayAlwaysExpanded"]));
            }
            set {
                this["SysTrayAlwaysExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string DefaultProgramsCategory {
            get {
                return ((string)(this["DefaultProgramsCategory"]));
            }
            set {
                this["DefaultProgramsCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TaskbarPosition {
            get {
                return ((int)(this["TaskbarPosition"]));
            }
            set {
                this["TaskbarPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DesktopLabelPosition {
            get {
                return ((int)(this["DesktopLabelPosition"]));
            }
            set {
                this["DesktopLabelPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DesktopIconSize {
            get {
                return ((int)(this["DesktopIconSize"]));
            }
            set {
                this["DesktopIconSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceSoftwareRendering {
            get {
                return ((bool)(this["ForceSoftwareRendering"]));
            }
            set {
                this["ForceSoftwareRendering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskbarIconSize {
            get {
                return ((int)(this["TaskbarIconSize"]));
            }
            set {
                this["TaskbarIconSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDesktopOverlayHotKey {
            get {
                return ((bool)(this["EnableDesktopOverlayHotKey"]));
            }
            set {
                this["EnableDesktopOverlayHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCairoMenuHotKey {
            get {
                return ((bool)(this["EnableCairoMenuHotKey"]));
            }
            set {
                this["EnableCairoMenuHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Win|Shift|D")]
        public string DesktopOverlayHotKey {
            get {
                return ((string)(this["DesktopOverlayHotKey"]));
            }
            set {
                this["DesktopOverlayHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Win|Shift|Z")]
        public string CairoMenuHotKey {
            get {
                return ((string)(this["CairoMenuHotKey"]));
            }
            set {
                this["CairoMenuHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FoldersOpenDesktopOverlay {
            get {
                return ((bool)(this["FoldersOpenDesktopOverlay"]));
            }
            set {
                this["FoldersOpenDesktopOverlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMenuBarBlur {
            get {
                return ((bool)(this["EnableMenuBarBlur"]));
            }
            set {
                this["EnableMenuBarBlur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMenuBarMultiMon {
            get {
                return ((bool)(this["EnableMenuBarMultiMon"]));
            }
            set {
                this["EnableMenuBarMultiMon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTaskbarMultiMon {
            get {
                return ((bool)(this["EnableTaskbarMultiMon"]));
            }
            set {
                this["EnableTaskbarMultiMon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Info")]
        public string LogSeverity {
            get {
                return ((string)(this["LogSeverity"]));
            }
            set {
                this["LogSeverity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullWidthTaskBar {
            get {
                return ((bool)(this["FullWidthTaskBar"]));
            }
            set {
                this["FullWidthTaskBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHibernate {
            get {
                return ((bool)(this["ShowHibernate"]));
            }
            set {
                this["ShowHibernate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TaskbarMiddleClick {
            get {
                return ((int)(this["TaskbarMiddleClick"]));
            }
            set {
                this["TaskbarMiddleClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windowsDefaultBackground")]
        public string DesktopBackgroundType {
            get {
                return ((string)(this["DesktopBackgroundType"]));
            }
            set {
                this["DesktopBackgroundType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int BingWallpaperStyle {
            get {
                return ((int)(this["BingWallpaperStyle"]));
            }
            set {
                this["BingWallpaperStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CairoBackgroundImagePath {
            get {
                return ((string)(this["CairoBackgroundImagePath"]));
            }
            set {
                this["CairoBackgroundImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CairoBackgroundImageStyle {
            get {
                return ((int)(this["CairoBackgroundImageStyle"]));
            }
            set {
                this["CairoBackgroundImageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CairoBackgroundVideoPath {
            get {
                return ((string)(this["CairoBackgroundVideoPath"]));
            }
            set {
                this["CairoBackgroundVideoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProgramsMenuLayout {
            get {
                return ((int)(this["ProgramsMenuLayout"]));
            }
            set {
                this["ProgramsMenuLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0")]
        public global::System.Windows.Point DesktopNavigationToolbarLocation {
            get {
                return ((global::System.Windows.Point)(this["DesktopNavigationToolbarLocation"]));
            }
            set {
                this["DesktopNavigationToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7820ae76-23e3-4229-82c1-e41cb67d5b9c|7820ae75-23e3-4229-82c1-e41cb67d5b9c|7820ae7" +
            "4-23e3-4229-82c1-e41cb67d5b9c|7820ae73-23e3-4229-82c1-e41cb67d5b9c")]
        public string PinnedNotifyIcons {
            get {
                return ((string)(this["PinnedNotifyIcons"]));
            }
            set {
                this["PinnedNotifyIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableTaskbarThumbnails {
            get {
                return ((bool)(this["EnableTaskbarThumbnails"]));
            }
            set {
                this["EnableTaskbarThumbnails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMenuExtraVolume {
            get {
                return ((bool)(this["EnableMenuExtraVolume"]));
            }
            set {
                this["EnableMenuExtraVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMenuExtraActionCenter {
            get {
                return ((bool)(this["EnableMenuExtraActionCenter"]));
            }
            set {
                this["EnableMenuExtraActionCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMenuExtraClock {
            get {
                return ((bool)(this["EnableMenuExtraClock"]));
            }
            set {
                this["EnableMenuExtraClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMenuExtraSearch {
            get {
                return ((bool)(this["EnableMenuExtraSearch"]));
            }
            set {
                this["EnableMenuExtraSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMenuBar {
            get {
                return ((bool)(this["EnableMenuBar"]));
            }
            set {
                this["EnableMenuBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTaskbarLabels {
            get {
                return ((bool)(this["ShowTaskbarLabels"]));
            }
            set {
                this["ShowTaskbarLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int TaskbarButtonWidth {
            get {
                return ((int)(this["TaskbarButtonWidth"]));
            }
            set {
                this["TaskbarButtonWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public int TaskbarButtonHeight {
            get {
                return ((int)(this["TaskbarButtonHeight"]));
            }
            set {
                this["TaskbarButtonHeight"] = value;
            }
        }
    }
}
